### PR TITLE
backdrop removal fix

### PR DESCRIPTION
**Pull request by mlessio**
This mod fixes the backdrop removal if the backdrop isn't a direct body child.

The backdrop inside another container isn't a standard bootstrap feature, but it is possible like in my case if using some external library that wraps the entire body content in an other div.

The standard behaviour remains totally working.

### CODE REVIEW

**Comment by pleerock** [comment]
Modal.ts should be the only changed file in your PR. Also check if RouteModal has same code and update it if required.

Configure your compiler to use tsconfig.json and never commit compiled files in PR

**Comment by paulthomas75** [comment]
It now seems to be possible to tab in the background...I know bootstrap 3 has added to their code:

 Modal.prototype.enforceFocus = function () {
    $(document)
      .off('focusin.bs.modal') // guard against infinite focus loop
      .on('focusin.bs.modal', $.proxy(function (e) {
        if (this.$element[0] !== e.target && !this.$element.has(e.target).length) {
          this.$element.focus()
        }
      }, this))
  }

I tried to fork your code but struggled to get the environment setup to try a fix for this, sorry I couldn't be more help.

**Comment by jdelucaa** [comment]
When is this fix going to be released?

**Comment by pleerock** [comment]
As you can see in readme this repository is not maintained anymore, consider making your own fork and make fix there.

**Comment by jdelucaa** [comment]
Sorry, I read readme after I commented here :$ Thanks!

**Pull request closed without merging**
